services:
  chroma:
    image: chromadb/chroma:0.5.5
    container_name: chroma
    ports:
    - 8000:8000
    volumes:
    - chroma-data:/chroma/chroma
    restart: unless-stopped
    networks:
    - shared-net
volumes:
  chroma-data: null
networks:
  shared-net:
    external: true
