services:
  pg:
    image: postgres:16-alpine
    container_name: pg
    environment:
      POSTGRES_PASSWORD: app
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
    - shared-net
volumes:
  pgdata: null
networks:
  shared-net:
    external: true
