services:
  weaviate:
    image: semitechnologies/weaviate:1.27.9
    container_name: weaviate
    ports:
    - 8080:8080
    - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: '25'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: none
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: node1
    volumes:
    - weaviate-data:/var/lib/weaviate
    restart: unless-stopped
    networks:
    - shared-net
volumes:
  weaviate-data: null
networks:
  shared-net:
    external: true
